server:
  port: 8070
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-img?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

logging:
  file:
    name: /data/log/fileUploader/fileUploader.log
  level:
    com:
      xiao: info


img-dir: /data/file/
img-download-url: https://littleshiba.cn/file/